### PR TITLE
Day 06

### PR DESCRIPTION
**Pull request by pradyumna100903**
Day 06

### CODE REVIEW

**Review by dhruvabhat24 — CHANGES_REQUESTED** [review]
Explanation is not enough.

**Comment by pradyumna100903** [comment]
Fixed all Conflicts and Added Day 07 Code too . Please Review

**Review by dhruvabhat24 — CHANGES_REQUESTED** [review]
Kindly provide the clear explanation for both problems else it will be marked as invalid.

**Review by pradyumna100903 — COMMENTED** [review]
Now is it Fine , Provided Clear approach for both codes.

**Review by dhruvabhat24 — APPROVED** [review]

**Pull request merged**
