### PR TITLE
Day 3

### PR DESCRIPTION
**Pull request by Abiji-2020**

### CODE REVIEW

**Review by dhruvabhat24 — CHANGES_REQUESTED** [review]
Upate the main readme with solution Link

**Comment by Abiji-2020** [comment]
In this repo there is no solution link in the main readme.md file may be you are saying in the DSA Cracker repo?

**Comment by dhruvabhat24** [comment]
https://github.com/dhruvabhat24/Leetcode-2024/tree/main/February#readme
kindly check this

**Comment by dhruvabhat24** [comment]
Even in DSA craker you havent updated the solution link in the readme.

**Review by dhruvabhat24 — APPROVED** [review]

**Pull request merged**
